import type { Room } from '@/app/types';

export const rooms: Room[] = [
  {
    slug: 'benicarlo',
    capacity: 2,
    area: 28,
    images: [
      '/images/rooms/ROOM6_4.jpg',
      '/images/rooms/ROOM6_1.jpg',
      /* '/images/rooms/ROOM6_2.jpg', */
      '/images/rooms/ROOM6_3.jpg',
      '/images/rooms/ROOM6_5.jpg',
      '/images/rooms/ROOM6_6.jpg',
    ],
    characteristics: [
      { icon: 'icon-2persons', name: '2guests' },
      { icon: 'icon-measures', name: '28m' },
      { icon: 'icon-bed', name: 'doubleBed' },
      { icon: 'icon-panoramic-view', name: 'panoramicView' },
    ],
    services: [
      { icon: 'icon-wifi', name: 'wifi' },
      { icon: 'icon-pool', name: 'pool' },
      { icon: 'icon-dine', name: 'restaurant' },
      { icon: 'icon-airc', name: 'airConditioning' },
      { icon: 'icon-tv', name: 'tv' },
      { icon: 'icon-shower', name: 'shower' },
      { icon: 'icon-light', name: 'thoughtfulLighting' },
      { icon: 'icon-design', name: 'chicDesign' },
      { icon: 'icon-towels', name: 'luxuryToiletries' },
    ],
  },
  {
    slug: 'traiguera',
    capacity: 2,
    area: 28,
    images: [
      /* '/images/rooms/ROOM7_1.jpg', */
      '/images/rooms/ROOM7_3.jpg',
      '/images/rooms/ROOM7_4.jpg',
      '/images/rooms/ROOM7_2.jpg',
      '/images/rooms/ROOM7_5.jpg',
    ],
    characteristics: [
      { icon: 'icon-2persons', name: '2guests' },
      { icon: 'icon-measures', name: '28m' },
      { icon: 'icon-bed', name: 'doubleBed' },
      { icon: 'icon-panoramic-view', name: 'panoramicView' },
    ],
    services: [
      { icon: 'icon-wifi', name: 'wifi' },
      { icon: 'icon-pool', name: 'pool' },
      { icon: 'icon-dine', name: 'restaurant' },
      { icon: 'icon-airc', name: 'airConditioning' },
      { icon: 'icon-tv', name: 'tv' },
      { icon: 'icon-shower', name: 'shower' },
      { icon: 'icon-light', name: 'thoughtfulLighting' },
      { icon: 'icon-design', name: 'chicDesign' },
      { icon: 'icon-towels', name: 'luxuryToiletries' },
    ],
  },
  {
    slug: 'la-mina',
    capacity: 2,
    area: 28,
    images: [
      '/images/rooms/ROOM_4_1.jpg',
      '/images/rooms/ROOM_4_2.jpg',
      '/images/rooms/ROOM_4_3.jpg',
      '/images/rooms/ROOM_4_4.jpg',
      '/images/rooms/ROOM_4_5.jpg',
    ],
    characteristics: [
      { icon: 'icon-2persons', name: '2guests' },
      { icon: 'icon-measures', name: '28m' },
      { icon: 'icon-bed', name: 'doubleBed' },
      { icon: 'icon-panoramic-view', name: 'panoramicView' },
    ],
    services: [
      { icon: 'icon-wifi', name: 'wifi' },
      { icon: 'icon-pool', name: 'pool' },
      { icon: 'icon-dine', name: 'restaurant' },
      { icon: 'icon-airc', name: 'airConditioning' },
      { icon: 'icon-tv', name: 'tv' },
      { icon: 'icon-jakuzzi', name: 'jakuzzi' },
      { icon: 'icon-light', name: 'softLighting' },
      { icon: 'icon-design', name: 'traditionalDesign' },
      { icon: 'icon-towels', name: 'luxuryToiletries' },
    ],
  },
  {
    slug: 'almenara',
    capacity: 2,
    area: 35,
    images: [
      '/images/rooms/ROOM_1_1.jpg',
      '/images/rooms/ROOM_1_2.jpg',
      '/images/rooms/ROOM_1_3.jpg',
      '/images/rooms/ROOM_1_4.jpg',
      '/images/rooms/ROOM_1_5.jpg',
      '/images/rooms/ROOM_1_6.jpg',
    ],
    characteristics: [
      { icon: 'icon-2persons', name: '2guests' },
      { icon: 'icon-measures', name: '35m' },
      { icon: 'icon-bed', name: 'doubleBed' },
      { icon: 'icon-panoramic-view', name: 'panoramicView' },
    ],
    services: [
      { icon: 'icon-wifi', name: 'wifi' },
      { icon: 'icon-pool', name: 'pool' },
      { icon: 'icon-dine', name: 'restaurant' },
      { icon: 'icon-airc', name: 'airConditioning' },
      { icon: 'icon-tv', name: 'tv' },
      { icon: 'icon-shower', name: 'shower' },
      { icon: 'icon-light', name: 'thoughtfulLighting' },
      { icon: 'icon-design', name: 'chicDesign' },
      { icon: 'icon-towels', name: 'luxuryToiletries' },
    ],
  },
  {
    slug: 'carlet',
    capacity: 2,
    area: 35,
    images: [
      '/images/rooms/ROOM_2_1.jpg',
      '/images/rooms/ROOM_2_2.jpg',
      '/images/rooms/ROOM_2_3.jpg',
      '/images/rooms/ROOM_2_4.jpg',
      '/images/rooms/ROOM_2_5.jpg',
    ],
    characteristics: [
      { icon: 'icon-2persons', name: '2guests' },
      { icon: 'icon-measures', name: '35m' },
      { icon: 'icon-bed', name: 'doubleBed' },
      { icon: 'icon-panoramic-view', name: 'panoramicView' },
    ],
    services: [
      { icon: 'icon-wifi', name: 'wifi' },
      { icon: 'icon-pool', name: 'pool' },
      { icon: 'icon-dine', name: 'restaurant' },
      { icon: 'icon-airc', name: 'airConditioning' },
      { icon: 'icon-tv', name: 'tv' },
      { icon: 'icon-shower', name: 'shower' },
      { icon: 'icon-light', name: 'thoughtfulLighting' },
      { icon: 'icon-design', name: 'chicDesign' },
      { icon: 'icon-towels', name: 'luxuryToiletries' },
    ],
  },
  {
    slug: 'the-red-sand-suite',
    capacity: 2,
    area: 50,
    images: [
      '/images/rooms/ROOM_3_4.jpg',
      '/images/rooms/ROOM_3_1.jpg',
      '/images/rooms/ROOM_3_2.jpg',
      '/images/rooms/ROOM_3_3.jpg',
      '/images/rooms/ROOM_3_5.jpg',
      '/images/rooms/ROOM_3_6.jpg'
    ],
    characteristics: [
      { icon: 'icon-2persons', name: '2guests' },
      { icon: 'icon-measures', name: '50m' },
      { icon: 'icon-bed', name: 'kingSizeBed' },
      { icon: 'icon-sofa', name: 'sofa' },
    ],
    services: [
      { icon: 'icon-wifi', name: 'wifi' },
      { icon: 'icon-pool', name: 'pool' },
      { icon: 'icon-dine', name: 'restaurant' },
      { icon: 'icon-airc', name: 'airConditioning' },
      { icon: 'icon-tv', name: 'tv' },
      { icon: 'icon-jakuzzi', name: 'jakuzzi' },
      { icon: 'icon-bar', name: 'minibar' },
      { icon: 'icon-design', name: 'stylishDecor' },
      { icon: 'icon-hiking', name: 'countrysideViews' },
      { icon: 'icon-towels', name: 'luxuryToiletries' },
    ],
  },
  {
    slug: 'cdg-retreat',
    capacity: 4,
    area: 60,
    images: [
      '/images/rooms/ROOM_5_1.jpg',
      '/images/rooms/ROOM_5_2.jpg',
      '/images/rooms/ROOM_5_3.jpg',
      '/images/rooms/ROOM_5_4.jpg',
      '/images/rooms/ROOM_5_5.jpg',
    ],
    characteristics: [
      { icon: 'icon-2persons', name: '4guests' },
      { icon: 'icon-measures', name: '60m' },
      { icon: 'icon-bed', name: '3beds' },
      { icon: 'icon-sofa', name: 'sofa' },
    ],
    services: [
      { icon: 'icon-wifi', name: 'wifi' },
      { icon: 'icon-pool', name: 'pool' },
      { icon: 'icon-dine', name: 'restaurant' },
      { icon: 'icon-airc', name: 'airConditioning' },
      { icon: 'icon-tv', name: 'tv' },
      { icon: 'icon-shower', name: 'shower' },
      { icon: 'icon-towels', name: 'luxuryToiletries' },
      { icon: 'icon-design', name: 'traditionalRuralCharacter' },
      { icon: 'icon-garden-view', name: 'gardenViews' },
      { icon: 'icon-terrace', name: 'roofTerrace' },
    ],
  },
];

export function getRoomBySlug(slug: string): Room | undefined {
  return rooms.find((room) => room.slug === slug);
}

export function getAllRoomSlugs() {
  return rooms.map((room) => ({ slug: room.slug }));
}
